name: Rust CI/CD

on:
  push:
    branches: [main, master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v6

      - name: ğŸ— Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c
        with:
          components: clippy, rustfmt

      - name: ğŸ§ª Run Cargo check
        run: cargo check

      - name: ğŸ§¹ Run Clippy
        run: cargo clippy -- -D warnings

      - name: ğŸ¨ Run Cargo fmt
        run: cargo fmt -- --check

  build:
    runs-on: ${{ matrix.runs-on.os }}
    name: build (${{ matrix.runs-on.os }}, ${{ matrix.build.profile }})
    timeout-minutes: 5
    strategy:
      matrix:
        runs-on:
          - os: ubuntu-latest
            binary_ext: ""

          - os: windows-latest
            binary_ext: .exe

        build:
          - profile: debug
            cargo_args: ""

          - profile: release
            cargo_args: --release

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v6

      - name: ğŸ— Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c

      - name: ğŸ—ï¸ Build (${{ matrix.runs-on.os }} / ${{ matrix.build.profile }})
        run: cargo build ${{ matrix.build.cargo_args }}

      - name: ğŸ“¦ Upload artifact (${{ matrix.runs-on.os }} / ${{ matrix.build.profile }})
        uses: actions/upload-artifact@v6
        with:
          name: pdup-rs-${{ matrix.runs-on.os }}-${{ matrix.build.profile }}
          path: target/${{ matrix.build.profile }}/pdup-rs${{ matrix.runs-on.binary_ext }}
          if-no-files-found: error
          retention-days: 7

  collect:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    timeout-minutes: 2
    needs:
      - test
      - build
    steps:
      - name: âœ”ï¸ Fail if any dependency failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
